libraries:              # Library mappings must have a colon (:) placed after them
  Movies:
    metadata_path:
      - file: config/imdbgenres.yml
      - git: meisnate12/Movies
      - git: meisnate12/MovieCharts
      - git: meisnate12/Holiday
      - git: meisnate12/Studios
  TV Shows:
    metadata_path:
      - git: meisnate12/ShowCharts
      - git: yozora/configs/tv/networks
settings:                  # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  assets_for_all: false
  sync_mode: append
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: true
  run_again_delay: 2
  missing_only_released: true
  create_asset_folders: false
  delete_below_minimum: false
  tvdb_language: default
  show_missing_assets: true
  asset_depth: 0
  dimensional_asset_rename: false
  show_missing_season_assets: false
  delete_not_scheduled: false
  only_filter_missing: false
  show_options: false
  ignore_ids:
  ignore_imdb_ids:
  minimum_items: 1
  download_url_assets: false
  default_collection_order:
  verify_ssl: true
  playlist_sync_to_users: all
  show_missing_episode_assets: false
  show_asset_not_needed: true
  item_refresh_delay: 0
  custom_repo:
plex:                       # Can be individually specified per library as well
  url: http://192.168.0.200:32400
  token: B4617sYhtnecRg2jyUAA
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:
  apikey: 42892bab10c1b3c94cdedd1977b4f5c5
  language: en
tautulli:                   # Can be individually specified per library as well
  url: http://192.168.0.200:8181
  apikey: 69b86c7a54864945a21193da4a4e8f40
radarr:                     # Can be individually specified per library as well
  url: http://192.168.0.200:7878
  token: 23b74bc4efb94e3ca3fbd200dc77fe45
  version: v3
  root_folder_path: /data/media/movies
  monitor: true
  availability: released
  quality_profile: 720 -> 4k
  tag:
  search: false
  add_existing: false
  radarr_path:
  plex_path:
  add_missing: false
sonarr:                      # Can be individually specified per library as well
  url: http://192.168.0.200:8989
  token: 0812777f12784a6897f902e58f6ec6a8
  version: v3
  root_folder_path: /data/media/tv
  monitor: true
  quality_profile: 480 -> 4k
  language_profile: Common Languages
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  add_existing: false
  sonarr_path:
  plex_path:
  add_missing: false
trakt:
  client_id: 03b18442cf5fe5771dd114891488b4593c21caaec8c06efd0e7815210003896a
  client_secret: 0bf58ccf7e68304a86cc57d09f58596923c4ce36d6881bc5850891b6dbacd05f
  authorization:
    access_token: aae9d9617b739e7a6018d4a542e748e000790f4ff24ecad8e8776ba4da2274a6
    token_type: Bearer
    expires_in: 7889237
    refresh_token: 425b664989a3ca3ecc5810ad4ae90a34ca24e2d4d490d822114e9915319859db
    scope: public
    created_at: 1641782748
